In this notebook we will learn how to create and train an embedding layer for the words appearing in a text data. We will then train a simple DNN based model to do sentiment analysis on this data. 

## Exercise

This is exercise 13.10 in [this](https://www.oreilly.com/library/view/hands-on-machine-learning/9781492032632/) book.

### Problem Statement

In this exercise you will download a dataset, split it, create a tf.data.Dataset to load it and preprocess it efficiently, then build and train a binary classification model containing an Embedding layer:

  - a. Download the [Large Movie Review Dataset](http://ai.stanford.edu/~amaas/data/sentiment/), which contains 50,000 movies reviews from the Internet Movie Database. The data is organized in two directories, train and test, each containing a pos subdirectory with 12,500 positive reviews and a neg subdirectory with 12,500 negative reviews. Each review is stored in a separate text file. There are other files and folders (including preprocessed bag-of-words), but we will ignore them in this exercise.
  
    
  - b. Split the test set into a validation set (15,000) and a test set (10,000).
  
  
  - c. Use tf.data to create an efficient dataset for each set.
  
  
  - d. Create a binary classification model, using a TextVectorization layer to preprocess each review. If the TextVectorization layer is not yet available (or if you like a challenge), try to create your own custom preprocessing layer: you can use the functions in the tf.strings package, for example lower() to make everything lowercase, regex_replace() to replace punctuation with spaces, and split() to split words on spaces. You should use a lookup table to output word indices, which must be prepared in the adapt() method.
  
  
  - e. Add an Embedding layer and compute the mean embedding for each review, multiplied by the square root of the number of words (see Chapter 16). This rescaled mean embedding can then be passed to the rest of your model.
  
  
  - f. Train the model and see what accuracy you get. Try to optimize your pipelines to make training as fast as possible.


  - g. Use TFDS to load the same dataset more easily: tfds.load("imdb_reviews").

In [1]:
import tensorflow as tf
import tensorflow.keras as keras
print('tensorflow version: {}'.format(tf.__version__))
print('keras version: {}'.format(keras.__version__))

tensorflow version: 2.1.0
keras version: 2.2.4-tf


In [2]:
import os
print('cwd: {}'.format(os.getcwd()))

cwd: /home/prarit/MachineLearningProjects/Word-Embeddings


### Downloading the Large Movie Review Dataset

In [3]:
# good tutorial on using wget: https://www.tecmint.com/download-and-extract-tar-files-with-one-command/
# turn off verbose output of wget using the flag -nv : https://shapeshed.com/unix-wget/#how-to-turn-off-verbose-output 
!wget -c -nv http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz -o - 

In [4]:
# uncompress the downloaded files
!tar xzf aclImdb_v1.tar.gz

Note that tensorflow also provides this dataset: https://www.tensorflow.org/api_docs/python/tf/keras/datasets/imdb

### Briefly Explore the Dataset

In [5]:
# list the files in the current working directory
os.listdir()

['README.md',
 '.gitignore',
 '.ipynb_checkpoints',
 '.git',
 'aclImdb',
 'Word-Embeddings.ipynb',
 'aclImdb_v1.tar.gz']

We see that aclImdb_v1.tar.gz was extracted to a folder called aclImdb. Let's see the contents of this file.

In [6]:
path = os.path.join(os.getcwd() , 'aclImdb')
contents = os.listdir(path)
print('The contents of aclImdb are: \n{}'.format(contents))

The contents of aclImdb are: 
['imdb.vocab', 'train', 'README', 'imdbEr.txt', 'test']


There is a README file in aclImdb, let us read it.

In [7]:
# read README
filepath = os.path.join(path, 'README')
with open(filepath, 'r') as f:
    print(f.read())

Large Movie Review Dataset v1.0

Overview

This dataset contains movie reviews along with their associated binary
sentiment polarity labels. It is intended to serve as a benchmark for
sentiment classification. This document outlines how the dataset was
gathered, and how to use the files provided. 

Dataset 

The core dataset contains 50,000 reviews split evenly into 25k train
and 25k test sets. The overall distribution of labels is balanced (25k
pos and 25k neg). We also include an additional 50,000 unlabeled
documents for unsupervised learning. 

In the entire collection, no more than 30 reviews are allowed for any
given movie because reviews for the same movie tend to have correlated
ratings. Further, the train and test sets contain a disjoint set of
movies, so no significant performance is obtained by memorizing
movie-unique terms and their associated with observed labels.  In the
labeled train/test sets, a negative review has a score <= 4 out of 10,
and a positive review has a scor

From README, we find that the train/test folder contains a 'pos' folder for positive reviews and a 'neg' for negative reviews along with .txt files containing urls of positive and negative reviews respectively. There are also some other files for bag-of-words features etc. 

Each train/test folder contains a total of 25000 reviews of which 12500 are positive reviews and 12500 are negative reviews.

Let's verify the above about the 'train' folder

In [8]:
train_path = os.path.join(path,'train')
print('contents of the train folder: \n{}'.format(os.listdir(train_path)))

contents of the train folder: 
['unsup', 'urls_pos.txt', 'pos', 'labeledBow.feat', 'unsupBow.feat', 'neg', 'urls_neg.txt', 'urls_unsup.txt']


In order to create a dataset, we need the path to all the reviews. We can create the corresponding list of paths using glob

In [9]:
import glob

In [10]:
# paths to the positive reviews in the training set
train_pos_path = os.path.join(train_path, 'pos', '*.txt')
train_pos_reviews = glob.glob(train_pos_path)
print('No. of train-set files with positive reviews: {}'.format(len(train_pos_reviews)))

No. of train-set files with positive reviews: 12500


In [11]:
# paths to the negative reviews in the training set
train_neg_path = os.path.join(train_path, 'neg', '*.txt')
train_neg_reviews = glob.glob(train_neg_path)
print('No. of train-set files with negative reviews: {}'.format(len(train_neg_reviews)))

No. of train-set files with negative reviews: 12500


let us give a brief look at a positive review. 

In [12]:
file = train_pos_reviews[0]
with open(file, 'r') as f:
    print(f.read())

I watch them all.<br /><br />It's not better than the amazing ones (_Strictly Ballroom_, _Shall we dance?_ (Japanese version), but it's completely respectable and pleasingly different in parts.<br /><br />I am an English teacher and I find some of the ignorance about language in some of these reviews rather upsetting. For example: the "name should scream don't watch. 'How she move.' Since when can movie titles ignore grammar?" <br /><br />There is nothing inherently incorrect about Caribbean English grammar. It's just not Canadian standard English grammar. Comments about the dialogue seem off to me. I put on the subtitles because I'm a Canadian standard English speaker, so I just AUTOMATICALLY assumed that I would have trouble understanding all of it. It wasn't all that difficult and it gave a distinctly different flavour as the other step movies I have seen were so American.<br /><br />I loved that this movie was set in Toronto and, in fact, wish it was even more clearly set there. I 

Later, we will like to load an preprocess all the data using tensorflow's data API, therefore let us quickly see how to read the same file as above but this time by using tensorflow's [TextLineDataset](https://www.tensorflow.org/api_docs/python/tf/data/TextLineDataset) method.

In [13]:
pos_fl0 = tf.data.TextLineDataset(file)
for item in pos_fl0:
    print(item)

tf.Tensor(b'I watch them all.<br /><br />It\'s not better than the amazing ones (_Strictly Ballroom_, _Shall we dance?_ (Japanese version), but it\'s completely respectable and pleasingly different in parts.<br /><br />I am an English teacher and I find some of the ignorance about language in some of these reviews rather upsetting. For example: the "name should scream don\'t watch. \'How she move.\' Since when can movie titles ignore grammar?" <br /><br />There is nothing inherently incorrect about Caribbean English grammar. It\'s just not Canadian standard English grammar. Comments about the dialogue seem off to me. I put on the subtitles because I\'m a Canadian standard English speaker, so I just AUTOMATICALLY assumed that I would have trouble understanding all of it. It wasn\'t all that difficult and it gave a distinctly different flavour as the other step movies I have seen were so American.<br /><br />I loved that this movie was set in Toronto and, in fact, wish it was even more c

Perfect! As expected, we see that the pos_fl0 contains a single item and it's value output matches the output of the previous code cell. 

### Preprocessing the reviews

Having, learnt how to use tf.data.TextLineData() method, we can now starting preprocessing the data. In order to do this, we notice that the review contains punctuation marks and html line break tags etc. We will have to write a preprocessing function to get rid of these. Additionally, we will also change all alphabets to lower case.

#### Removing line-brk tags

This can be very simply done by using the .replace() method of python strings. We can therefore use it to replace all occurrances of the line-break tag with a space. In tensorflow, the equivalent method is [tf.strings.regex_replace()](https://www.tensorflow.org/api_docs/python/tf/strings/regex_replace).

#### tf.strings.regex_replace
Note that 'regex' in regex_replace() stands for ["regular expression"](https://docs.python.org/3/howto/regex.html). For e.g. the following will work:

In [14]:
tf.strings.regex_replace('hello','e','E')

<tf.Tensor: shape=(), dtype=string, numpy=b'hEllo'>

But the following will throw an error: tf.strings.regex_replace('h(llo', '(','E')

This is because "(" is a metacharacter. To match and replace meta-characters, we must prepend a backslash before them. This can be done as follows: '\\\\' + char. 

The previous code cell can now be made to work

In [15]:
# The error thrown by this code cell is intentional
tf.strings.regex_replace('h(llo', '\\'+'(','E')

<tf.Tensor: shape=(), dtype=string, numpy=b'hEllo'>

or equivalently:

In [16]:
tf.strings.regex_replace('h(llo','\(','E')

<tf.Tensor: shape=(), dtype=string, numpy=b'hEllo'>

##### Imp: 

Note that backslash itself is also a  meta-character. To search and replace backslash, we do the following:

In [17]:
tf.strings.regex_replace('h\llo', '\\'+'\\', 'E')

<tf.Tensor: shape=(), dtype=string, numpy=b'hEllo'>

or equivalently:

In [18]:
# we use '\\\\' and NOT '\\' to search and replace a backslash
tf.strings.regex_replace('h\llo', '\\\\', 'E')

<tf.Tensor: shape=(), dtype=string, numpy=b'hEllo'>

We now try three different ways of removing punctuations from a tensorflow string and compare their timings:

1) punc_filter_and_to_lower1: use tf.strings.unicode_decode() to convert all the characters in the string into an array of their ascii codes. We then loop through this array, skipping over the places where the entry matches the ascii code of a punctuation. Finally we call tf.strings.unicode_encode() on this array to convert the ascii codes back to characters, thereby obtaining a string with all the punctuations stripped. 


2) punc_filter_and_to_lower2: use tf.regex_replace() to search and replace each punctuation by empty space. Pay special attention to prepend backslash in order to be able to use meta-characters in regex_replace.


3) punc_filter_and_to_lower3: simply extract the python string using its .numpy() method. Then simple iterate through the characters of the string, skipping over the punctutations. Join the resulting list of character using .join() method. 

4) punc_filter_and_to_lower4: Use [tfds.features.text.Tokenizer()](https://www.tensorflow.org/datasets/api_docs/python/tfds/features/text/Tokenizer) by setting it's "alphanum_only" arg to True. This way it will only parse alpha-numeric characters in the text and to split the text at occurrances of non-alphanumeric characters. Since whitespace is a non-alpha-numeric character, the output will largely consist of a list of words in the text.  The caeat with this approach is that words with apostrophe in them such as " don't " will be split into two words: "don" and "t". Also, [tfds.features.text.Tokenizer()](https://www.tensorflow.org/datasets/api_docs/python/tfds/features/text/Tokenizer) does NOT consider underscores as non-alpha-numeric, so underscores do not get removed form the text. On the other hand since, the tokenizer already generates a list of words, we use this list to generate a vocobulary of words in the dataset at this step it-self, making the preprocessing faster.

There timing on the first review in the training set was as follows:

1) punc_filter_and_to_lower1: Wall time: ~ 3 s

2) punc_filter_and_to_lower2: Wall time: ~ 8 ms

3) punc_filter_and_to_lower3: Wall time: ~ 6 ms

4) punc_filter_and_to_lower4: Wall time: ~ 6 ms (when not udating a vocabulary of words) 

5) 4) punc_filter_and_to_lower4: Wall time: ~ 7 ms (when also udating a vocabulary of words) 

Clearly, the last function is the fastest with the first one being extremely slow (takes several secs). 

In [19]:
import string

In [20]:
# list of punctuations
punc_ls = string.punctuation
print('punctuations before utf encoding: {}'.format(punc_ls))
punc_ls2 = tf.strings.unicode_decode(punc_ls, input_encoding = 'UTF-8')
print('punctuations after utf encoding: \n{}'.format(punc_ls2))

punctuations before utf encoding: !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
punctuations after utf encoding: 
[ 33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  58  59  60
  61  62  63  64  91  92  93  94  95  96 123 124 125 126]


In [21]:
# function to get rid of punctuations, html line breaks and change to lower case
# using tf.strings.unicode_encode(), tf.strings.unicode_decode()
def punc_filter_and_to_lower1(st):
    
    # before removing punctuations, we should remove the html line-break tag
    # this is because the line break tag contains <,/ and > characters which 
    # will be removed if we remove punctuations first. This will then make it harder 
    # to identify the line-break-tag
    line_brk_tag = "<br /><br />" 
    st2 = tf.strings.regex_replace(st, line_brk_tag, ' ') # regex stands for regular expressions
                                                          # i.e. they are not metacharacters
                                                          # https://docs.python.org/3/howto/regex.html#matching-characters
    
    # now we replace all the punctions in the string
    st2 = tf.strings.unicode_decode(st2, input_encoding = 'utf-8')
    st2 = tf.strings.unicode_encode([char for char in st2 if char not in punc_ls2], output_encoding = 'UTF-8')
    
    st2 = tf.strings.lower(st2)
    
    return st2

In [22]:
import time

In [23]:
%%time
for item in pos_fl0:
    lst = punc_filter_and_to_lower1(item)

CPU times: user 3.43 s, sys: 46.6 ms, total: 3.47 s
Wall time: 3.47 s


In [24]:
lst

<tf.Tensor: shape=(), dtype=string, numpy=b'i watch them all its not better than the amazing ones strictly ballroom shall we dance japanese version but its completely respectable and pleasingly different in parts i am an english teacher and i find some of the ignorance about language in some of these reviews rather upsetting for example the name should scream dont watch how she move since when can movie titles ignore grammar  there is nothing inherently incorrect about caribbean english grammar its just not canadian standard english grammar comments about the dialogue seem off to me i put on the subtitles because im a canadian standard english speaker so i just automatically assumed that i would have trouble understanding all of it it wasnt all that difficult and it gave a distinctly different flavour as the other step movies i have seen were so american i loved that this movie was set in toronto and in fact wish it was even more clearly set there i loved that the heroine was so atypic

In [25]:
# function to get rid of punctuations, html line breaks and change to lower case
# using tf.strings.regex_replace()
def punc_filter_and_to_lower2(st):
    
    # before removing punctuations, we should remove the html line-break tag
    # this is because the line break tag contains <,/ and > characters which 
    # will be removed if we remove punctuations first. This will then make it harder 
    # to identify the line-break-tag
    line_brk_tag = "<br /><br />" 
    st2 = tf.strings.regex_replace(st, line_brk_tag, ' ')
    
    # now we replace all the punctions in the string
    for punc in punc_ls:
        # V.imp: to replace meta-characters we prepend a backslash to them 
        # infact we can also prepend a backslach before all the characters
        # to prepend a backslash before a character we do: '\\' + char
        st2 = tf.strings.regex_replace(st2, '\\'+ punc, ' ')
    
    st2 = tf.strings.lower(st2)
    
    return st2

In [26]:
%%time
for item in pos_fl0:
    lst = punc_filter_and_to_lower2(item)

CPU times: user 8.49 ms, sys: 93 µs, total: 8.58 ms
Wall time: 7.25 ms


In [27]:
lst

<tf.Tensor: shape=(), dtype=string, numpy=b'i watch them all  it s not better than the amazing ones   strictly ballroom    shall we dance    japanese version   but it s completely respectable and pleasingly different in parts  i am an english teacher and i find some of the ignorance about language in some of these reviews rather upsetting  for example  the  name should scream don t watch   how she move   since when can movie titles ignore grammar    there is nothing inherently incorrect about caribbean english grammar  it s just not canadian standard english grammar  comments about the dialogue seem off to me  i put on the subtitles because i m a canadian standard english speaker  so i just automatically assumed that i would have trouble understanding all of it  it wasn t all that difficult and it gave a distinctly different flavour as the other step movies i have seen were so american  i loved that this movie was set in toronto and  in fact  wish it was even more clearly set there  i 

In [28]:
# function to get rid of punctuations, html line breaks and change to lower case
# using .join() method in python string class
def punc_filter_and_to_lower3(st):
    
    # before removing punctuations, we should remove the html line-break tag
    # this is because the line break tag contains <,/ and > characters which 
    # will be removed if we remove punctuations first. This will then make it harder 
    # to identify the line-break-tag
    line_brk_tag = "<br /><br />" 
    st2 = tf.strings.regex_replace(st, line_brk_tag, ' ') # regex stands for regular expressions
                                                          # i.e. they are not metacharacters
                                                          # https://docs.python.org/3/howto/regex.html#matching-characters
    
    # now we replace all the punctions in the string
    st2 = st2.numpy().decode('utf-8')
    st2 = ''.join([char for char in st2 if char not in punc_ls])
    
    st2 = st2.lower()
    
    st2 = tf.convert_to_tensor(st2)
    
    return st2

In [29]:
%%time
for item in pos_fl0:
    lst = punc_filter_and_to_lower3(item)

CPU times: user 4.65 ms, sys: 121 µs, total: 4.77 ms
Wall time: 4.23 ms


In [30]:
lst

<tf.Tensor: shape=(), dtype=string, numpy=b'i watch them all its not better than the amazing ones strictly ballroom shall we dance japanese version but its completely respectable and pleasingly different in parts i am an english teacher and i find some of the ignorance about language in some of these reviews rather upsetting for example the name should scream dont watch how she move since when can movie titles ignore grammar  there is nothing inherently incorrect about caribbean english grammar its just not canadian standard english grammar comments about the dialogue seem off to me i put on the subtitles because im a canadian standard english speaker so i just automatically assumed that i would have trouble understanding all of it it wasnt all that difficult and it gave a distinctly different flavour as the other step movies i have seen were so american i loved that this movie was set in toronto and in fact wish it was even more clearly set there i loved that the heroine was so atypic

In [31]:
# function to get rid of punctuations, html line breaks and change to lower case
# using tfds.features.text.tokenizer()
# we will also simultaneously generate a vocabulary in this step
import tensorflow_datasets as tfds
def punc_filter_and_to_lower4(st, vocab = None):
    ''' vocab: vocabulary to update with the words in st'''
    
    # before removing punctuations, we should remove the html line-break tag
    # this is because the line break tag contains <,/ and > characters which 
    # will be removed if we remove punctuations first. This will then make it harder 
    # to identify the line-break-tag
    line_brk_tag = "<br /><br />" 
    st2 = tf.strings.lower(tf.strings.regex_replace(st, line_brk_tag, ' '))
    
    # now we replace all the punctions in the string
    tokenizer = tfds.features.text.Tokenizer()
    words = tokenizer.tokenize(st2.numpy()) # note that the inpout has to be a python string NOT as tensor 
                                            # The output is a list NOT a tensor
                                            # https://stackoverflow.com/questions/56665868/tensor-numpy-not-working-in-tensorflow-data-dataset-throws-the-error-attribu
    st2 = tf.strings.join(words, ' ')
    
    if type(vocab) == set:
        vocab.update(words)
        return st2, vocab
    
    
    return st2

In [32]:
%%time
for item in pos_fl0:
    lst = punc_filter_and_to_lower4(item)

CPU times: user 7.57 ms, sys: 0 ns, total: 7.57 ms
Wall time: 6.48 ms


In [33]:
lst

<tf.Tensor: shape=(), dtype=string, numpy=b'i watch them all it s not better than the amazing ones _strictly ballroom_ _shall we dance _ japanese version but it s completely respectable and pleasingly different in parts i am an english teacher and i find some of the ignorance about language in some of these reviews rather upsetting for example the name should scream don t watch how she move since when can movie titles ignore grammar there is nothing inherently incorrect about caribbean english grammar it s just not canadian standard english grammar comments about the dialogue seem off to me i put on the subtitles because i m a canadian standard english speaker so i just automatically assumed that i would have trouble understanding all of it it wasn t all that difficult and it gave a distinctly different flavour as the other step movies i have seen were so american i loved that this movie was set in toronto and in fact wish it was even more clearly set there i loved that the heroine was

In [34]:
%%time
# test the timing of punc_filter_and_to_lower4 when simultaneously updating a dictionary
vocab2 = set([])
for item in pos_fl0:
    lst, vocab2 = punc_filter_and_to_lower4(item, vocab2)

CPU times: user 7.49 ms, sys: 209 µs, total: 7.69 ms
Wall time: 7.28 ms


### Build a Vocabulary based on the training data

This can be easily done using python's [set()](https://docs.python.org/3.8/library/stdtypes.html#set-types-set-frozenset) container.: basically, split each text in the training instance into words and update the set with this list. This will add any new words in the text to the set. In the end, the set will contain all the unique words in the training dataset.

Note that we have also implemented the above idea in our function punc_filter_and_to_lower4() 

In [35]:
# function to create a vocabulary using the set() container
vocab1 = set([]) # python set for containing unique words in the training dataset
def vocab_builder1(strng):
    # split the string into its words
    words = tf.strings.split(strng)
    # update vocab
    vocab1.update(words.numpy())
    return

In [36]:
%%time
for item in pos_fl0:
    item = punc_filter_and_to_lower3(item)
    vocab_builder1(item)

CPU times: user 269 ms, sys: 55.1 ms, total: 325 ms
Wall time: 323 ms


Note that the vocab_builder1() function as defined above takes about 300 ms. On the otherhand, in punc_filter_and_to_lower4() function,  we were able to get almost the same result (upto the caveats mentioned in the previous section) by using tfds.features.text.Tokenizer(), in about 8 ms. Clearly, there is a difference of few order of magnitude between the time taken by the two routines with the difference between their output being quite tolerable.  

#### building the vocabulary

In [37]:
vocab = set([])
train_filepaths = tf.data.Dataset.list_files([train_pos_path, train_neg_path])
train_dataset = tf.data.TextLineDataset(train_filepaths)

ctr = 0
for item in train_dataset:
    _ , vocab = punc_filter_and_to_lower4(item, vocab)
    
    ctr+=1
    if ctr%255 ==0:
        print("=", end = '')

In [38]:
# pick 5 random words from vocab to inspect it
import random

random.sample(vocab, 5)

['okej', 'strewn', 'critiscism', 'gloating', 'zit']

In [39]:
print('no. of words in vocabulary: {}'.format(len(vocab)))

no. of words in vocabulary: 74893


### Create a lookup table based on the vocabulary

In [40]:
indices = tf.range(len(vocab), dtype = tf.int64)
lookup_initializer = tf.lookup.KeyValueTensorInitializer( list(vocab), indices) 
num_oov_buckets = 50 
lookup_table = tf.lookup.StaticVocabularyTable( initializer = lookup_initializer, 
                                               num_oov_buckets = num_oov_buckets)

In [41]:
# function to map a text to integers using the above lookup table
def text_to_integers(X):
    X = tf.strings.split(X)
    int_ls = lookup_table.lookup(X)
    return int_ls

In [42]:
for item in pos_fl0:
    item = punc_filter_and_to_lower4(item)
    item = text_to_integers(item)
    print(item)

tf.Tensor(
[14407 58873  4975 69751 23242 53985 26925 74297 74002  7234 33777 14061
 24305 41997 28979 10854 22754 17037  9513 71062 74253 23242 53985   666
 21575 31566  9440 68180 51457 72708 14407 43549  4556 57045 33588 31566
 14407  2899  3443 53730  7234 57531 35046 27833 51457  3443 53730 73798
 61774 65314 53323 67509 11690  7234 48045 16591 49577 38757 54738 58873
 67806 62527 43295 26847 73294   904 66560 69518  9479 69467 42413 67404
 12509 12102 13956 35046 18379 57045 69467 23242 53985 40530 26925 61199
 46624 57045 69467 49538 35046  7234 46449 32013 71807  3809 55572 14407
 18524 51385  7234 49297  5559 14407 51597  9114 61199 46624 57045  4189
 29750 14407 40530 39666 61590 28164 14407 49750 55549 39889  4438 69751
 53730 23242 23242 65499 54738 69751 28164 28451 31566 23242 73744  9114
 17745 68180 33195 29302  7234 74301 46796 71236 14407 55549   135 14822
 29750 53187 14407 59298 28164 68165 66560 27927 52059 51457 22376 31566
 51457 34050 19358 23242 27927 14912 462

### Create an Embedding Matrix

In [43]:
embedding_dim = 100
initial_embeddings = tf.random.uniform([len(vocab) + num_oov_buckets, embedding_dim] ) 
embedding_matrix = tf.Variable(initial_embeddings)
embedding_matrix

<tf.Variable 'Variable:0' shape=(74943, 100) dtype=float32, numpy=
array([[0.27821112, 0.9385762 , 0.7214955 , ..., 0.6498685 , 0.8854619 ,
        0.30109215],
       [0.6042515 , 0.19952965, 0.9578979 , ..., 0.3977008 , 0.5859591 ,
        0.9243921 ],
       [0.591275  , 0.46339405, 0.59744716, ..., 0.5441897 , 0.73397696,
        0.5774808 ],
       ...,
       [0.0693773 , 0.39532983, 0.7935848 , ..., 0.16767669, 0.54799306,
        0.5737673 ],
       [0.8727343 , 0.50011694, 0.7078893 , ..., 0.99221504, 0.9465153 ,
        0.63276553],
       [0.12636709, 0.40288007, 0.18929994, ..., 0.7660638 , 0.52223146,
        0.05493701]], dtype=float32)>

In [44]:
# function to create an embedding-vector from a list of word indices
def indices_to_embeddings(idxs):
    embeddings = tf.nn.embedding_lookup(embedding_matrix, idxs)
    sqrt_num_words = tf.math.sqrt(tf.cast(tf.size(idxs), tf.float32)) # size is of type int32 but 
                                                                      # tf.math.sqrt has to have one of 
                                                                      # bfloat16, half, float32, 
                                                                      # float64, complex64, 
                                                                      # complex128.
    mean_embedding = tf.math.reduce_mean(embeddings, axis = 0)
    sentence_embedding = tf.multiply(sqrt_num_words, mean_embedding)
    return sentence_embedding

In [45]:
for item in pos_fl0:
    item = punc_filter_and_to_lower4(item)
    item = text_to_integers(item)
    item = indices_to_embeddings(item)

In [46]:
item

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([7.8804903, 7.9428205, 8.321264 , 8.704269 , 8.907119 , 7.297222 ,
       7.8233023, 8.103945 , 8.492896 , 7.055711 , 7.928911 , 7.2358847,
       7.948384 , 7.3605404, 8.088991 , 8.656651 , 6.813101 , 7.492557 ,
       7.6973166, 7.2751703, 7.442708 , 8.090645 , 6.679673 , 6.9293613,
       8.752965 , 7.1476398, 7.7636847, 7.5437517, 8.52123  , 7.0815763,
       8.814794 , 8.5974655, 8.198473 , 6.6910563, 6.8116493, 9.128407 ,
       7.8052697, 8.204603 , 7.209249 , 7.2705297, 7.812039 , 7.356413 ,
       8.261715 , 7.5293274, 8.118498 , 8.420315 , 8.838265 , 7.810327 ,
       8.174669 , 7.1887155, 7.638866 , 7.5661545, 7.3809075, 7.9660535,
       7.982779 , 7.776999 , 7.387608 , 7.168912 , 8.28974  , 7.2365117,
       8.203039 , 7.347867 , 7.7058563, 8.465302 , 7.2081594, 7.844795 ,
       8.32972  , 7.518017 , 8.138895 , 7.9976125, 7.2368646, 8.569483 ,
       7.309824 , 7.5620494, 7.581903 , 8.855443 , 8.150174 , 7.189464 ,
   

### Create a Preprocessing layer

Let us now define a preprocessing layer that accepts a sentence as an input, removes punctuations and line-brk tags form it, then converts it's words into indices and finally output an embedding vector corresponding to the sentence.

In [47]:
class Preprocessing_layer(keras.layers.Layer): 
    def __init__(self, vocab,  num_oov_buckets, embedding_len, **kwargs): 
        super().__init__(**kwargs)
        self.vocab = vocab
        self.vocab_len  = tf.size(vocab) 
        self.num_oov_buckets = num_oov_buckets
        self.embedding_len = embedding_len
        self.indices = tf.range(self.vocab_len, dtype = tf.int64)
        self.lookup_intializer = tf.lookup.KeyValueTensorInitializer(list(self.vocab),
                                                                     self.indices)
        self.lookup_table = tf.lookup.StaticVocabularyTable(initializer = self.lookup_initializer, 
                                                            num_oov_buckets = self.num_oov_buckets)
         
    # build the embedding matrix 
    def build(self, batch_input_shape):
        self.embedding_mat = self.add_weight(name = 'embedding matrix', 
                                             shape = [self.vocab_len + self.num_oov_buckets, self.embedding_len],
                                             initializer = tf.random_uniform_initializer)
        
        super().build(batch_input_shape)
        
    
    # function to convert a sentence into a list of indices for its words
    def text_to_integers(self, X):
        X = tf.strings.split(X)
        return lookup_table.lookup(X)
    
    # function to convert a list of indices into an embedding vector
    def integers_to_embeddings(self, X):
        sqrt_num_words = tf.math.sqrt(tf.cast(tf.size(X), tf.float32))
        X = tf.nn.embedding_lookup(self.embedding_mat, X)
        X = tf.math.reduce_mean(X, axis = 0) 
        
        return tf.multiply(sqrt_num_words, X)
        
    # define the call method
    def call(self, X):
        
        # recall X is a string with all the punctuations etc removed
        # We first convert all its words into their indices
        X = self.text_to_integers(X)
        # now convert this a mean embedding vector
        X = self.integers_to_embeddings(X)
        
        return X

### Labeling the data

Note that the positive and negative reviews in each dataset have been stored in seperate folders and as such they have no explicit labels. We will therefore have to create our own labels as was done in [this](https://www.tensorflow.org/tutorials/load_data/text) official tensorflow tutorial. 

In [48]:
# function to return apply a label
def labeler(review, label):
    return review, tf.cast(label, tf.int64)

In [49]:
train_pos_paths = tf.data.Dataset.list_files(train_pos_path)
train_pos_reviews = tf.data.TextLineDataset(train_pos_paths).map(lambda x : labeler(x, 1))

In [50]:
for item in train_pos_reviews.take(2):
    print(item)
    print(' ')

(<tf.Tensor: shape=(), dtype=string, numpy=b'You will marvel at the incredibly sophisticated computer animation, and the novelty probably won\'t wear off on the first, second or third viewing, but you?ll be drawn in by the characters which are so simple yet intriguing, that you may find yourself actually caring for them in an unexpected way, which may or may not make you feel a little childish due to the medium.<br /><br />Disney continues to firmly hold the title of "Greatest Animation in the World", with "A Bug?s Life" standing as one of their greatest achievements. One of the innovative attachments being the delightful "out-takes" added to the end of the film. The DVD has two sets of these out-takes where as I?m told the VHS cassette has one alternating version per tape. The DVD also features "Gerry?s Game" which is a delightful little PIXAR short that was also shown prior to the film in theaters.<br /><br />This is by far the superior insect-film in comparison to Dreamworks? "Antz"

In [51]:
train_neg_paths = tf.data.Dataset.list_files(train_neg_path)
train_neg_reviews = tf.data.TextLineDataset(train_neg_paths).map(lambda x: labeler(x, 0))

In [52]:
for item in train_neg_reviews.take(2):
    print(item)
    print(' ')

(<tf.Tensor: shape=(), dtype=string, numpy=b'Pictures that usually glorify a hero have meaning. As an example, Bonnie and Clyde glorified the dynamic bank robbers and you actually felt sympathy for them despite their evil deeds. Why? They were two people caught up in the depression when people were desperate to survive.<br /><br />This film has absolutely no substance. The Viggo Mortensen character soon emerges as a folk hero. Why? He speeds along an Idaho highway on the way to the hospital where his stricken wife has been taking. No one bothers to understand why he is trying to flee everyone. Even worse, when the realization becomes apparent that he is not a red-neck terrorist, no one in government wants to help him as they try to save their rear ends.<br /><br />Jason Priestley co-stars as a radio emcee who builds upon the story in support of our hero.<br /><br />The ending is absolutely unbelievable.'>, <tf.Tensor: shape=(), dtype=int64, numpy=0>)
 
(<tf.Tensor: shape=(), dtype=stri

### Creating training batches

In [53]:
shuffle_buffer_size = 20000
train_dataset = train_pos_reviews.concatenate(train_neg_reviews).shuffle(buffer_size = shuffle_buffer_size)

In [54]:
count = 0
for item in train_dataset:
    count+=1
print(count)    

25000


We now wish to apply punc_filter_and_to_lower4() to the reviews in our training dataset. For this we will use the [map](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#map) method of tf.data.Datasets. At this point it is important to note that (as mentioned in the documentation for [map](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#map)):

    Note that irrespective of the context in which map_func is defined (eager vs. graph), tf.data traces the function and executes it as a graph. To use Python code inside of the function you have two options:

     1) Rely on AutoGraph to convert Python code into an equivalent graph computation. The downside of this approach is that AutoGraph can convert some but not all Python code.

     2) Use tf.py_function, which allows you to write arbitrary Python code but will generally result in worse performance than 1)

This point is of concern to us because the [tokenizer](https://www.tensorflow.org/datasets/api_docs/python/tfds/features/text/Tokenizer) we used in punc_filter_and_to_lower4() only accepts string input and NOT tensors. This string was extracted from the tensor using its .numpy() method which is only operable in eager mode. Thus when we pass punc_filter_and_to_lower4() to map(), it throws an error, complaining:

     'Tensor' object has no attribute 'numpy'


Thus we have to wrap punc_filter_and_to_lower4() with tf.py_function before passing it to map


In [55]:
# function to wrap punc_filter_and_to_lower4 with tf.py_function
# we will also use tf.ensure_shape(), or else tensorflow is 
# unable to statically determine it, leading to error being thrown during training
def string_transform(X):
    x = tf.py_function(punc_filter_and_to_lower4, [X], Tout = tf.string)
    x = tf.ensure_shape(x, ())
    
    return x

batch_size = 50
prefetch = 2
train_batch = train_dataset.map(lambda X, y: 
                                    (string_transform(X), y) ).batch(batch_size).prefetch(prefetch)

Note that we could have alternatively, preprocessed the data using punc_filter_and_to_lower2() which is based on tensorflow functions and then used it. The price we would have to pay is to rebuild the vocabulary accordingly. 

In [56]:
ite = next(iter(train_batch))
print('shape of train-batch: {}'.format(ite[0].shape))
print(ite[0][0])

shape of train-batch: (50,)
tf.Tensor(b'i hate to sound like an old person but frankly i haven t seen too many movies that i like that were made after 1960 generally movies just seem to get worse and worse although i quite enjoyed the scott baio vehicle the bread my sweet except for the de rigeur sex scene which added nothing of value to that movie this movie makes the mother a former las vegas chorus girl seem to be incapable of surviving on her own although she is clearly in her 50s though hinted at being in her 40s i didn t buy it i m 57 and like all the women i know in their 50s and 40s more than capable of surviving on my own as i have been doing since i graduated from high school at 13 got legally emancipated and set off on my own life s journey the daughter is not believable in her job role she gets a promotion she doesn t deserve a great opportunity and drops that ball too but when another female employee steps up to the plate and is ready to deliver the writers shoot her down 

In [57]:
ite[1]

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1])>

### Create Validation dataset 

As instructed in the excercise, we will create a validation dataset by splitting the test set into half

In [58]:
test_path = os.path.join(path, 'test')
print(test_path)
test_pos_path = os.path.join(test_path, 'pos', '*.txt')
print('path to positive test reviews: \n{}'.format(test_pos_path))
test_neg_path = os.path.join(test_path, 'neg', '*.txt')
print('path to negative test reviews: \n{}'.format(test_neg_path))

/home/prarit/MachineLearningProjects/Word-Embeddings/aclImdb/test
path to positive test reviews: 
/home/prarit/MachineLearningProjects/Word-Embeddings/aclImdb/test/pos/*.txt
path to negative test reviews: 
/home/prarit/MachineLearningProjects/Word-Embeddings/aclImdb/test/neg/*.txt


In [59]:
test_pos_files = glob.glob(test_pos_path)
len(test_pos_files)

12500

In [60]:
valid_size = 12500
valid_pos_files = random.sample(test_pos_files, int(valid_size/2))
len(valid_pos_files)

6250

In [61]:
# We can remove the valid_pos_files from the set of test_pos_files through the
# simple trick explained in the following post:
# https://stackoverflow.com/questions/6486450/python-compute-list-difference/6486467
test_pos_files = list(set(test_pos_files) - set(valid_pos_files))
len(test_pos_files)

6250

In [62]:
test_neg_files = glob.glob(test_neg_path)
print('initial test_neg_files len:{}'.format(len(test_neg_files)))
valid_neg_files = random.sample(test_neg_files, int(valid_size/2))
print('valid_neg_files len: {}'.format(len(valid_neg_files)))
test_neg_files = list(set(test_neg_files) - set(valid_neg_files))
print('test_neg_files len: {}'.format(len(test_neg_files)))

initial test_neg_files len:12500
valid_neg_files len: 6250
test_neg_files len: 6250


In [63]:
valid_pos_reviews = tf.data.TextLineDataset(valid_pos_files).map(lambda x: labeler(x, 1))
valid_neg_reviews = tf.data.TextLineDataset(valid_neg_files).map(lambda x: labeler(x, 0))

In [64]:
for item in valid_pos_reviews.take(2):
    print(item)
    print(' ')

(<tf.Tensor: shape=(), dtype=string, numpy=b"It was high time a movie about the situation in a largely ignored Asian country like Myanmar had to be made and Beyond Rangoon is Hollywood's answer. Initially I thought Hollywood would dramatize the events of the 8888 uprising and add in the traditionally Hollywood spice of Titanic-type love between the lead heroine and the Burmese male lead who happens to be an old man. Thankfully, nothing of that sort was in place - which may also explain why the film was not financially successful.<br /><br />Anyway, the film was honest-to-God and I was glad at the accuracy of events portrayed. Apart from the fact that filming was done outside of Myanmar in Malaysia & Thailand and that I missed the exotic Burmese locales, I could not find much fault in the film.<br /><br />You cannot blame the film for the desperation of the people and the resulting overwhelming actions. It is after all, real events of a civil war. The music by Hans Zimmer is definitely 

In [65]:
for item in valid_neg_reviews.take(2):
    print(item)
    print(' ')

(<tf.Tensor: shape=(), dtype=string, numpy=b"I cannot believe I actually set up a 'season pass' on my TiVo for this, apparently they had a good preview or something .. I can't imagine it though. After seeing about 5 minutes I thought to myself.. why am I watching this.. It is definitely not reality, and some of the worst acting I have ever seen on television.. I am a total addict of reality TV and there is nothing real about this. THE ACTING.. (if you can call it that) is awful.. The only ones that are almost 5% decent are the girls that are meant to draw viewers to the show.. although they would need to be a lot prettier to save this train wreck.. if they would have more lines they would probably change my mind as they probably have no talent either. This is obviously a very low budget production with 'actors' who are apparently very cheap. There is no way they could get a job in anything else. Someone needs to direct these people to a job in food service.. Maybe they could do that. O

In [66]:
test_pos_reviews = tf.data.TextLineDataset(test_pos_files).map(lambda x: labeler(x, 1))
test_neg_reviews = tf.data.TextLineDataset(test_neg_files).map(lambda x: labeler(x, 0))

In [67]:
for item in test_pos_reviews.take(2):
    print(item)
    print(' ')

(<tf.Tensor: shape=(), dtype=string, numpy=b'Harry Langdon\'s "Saturday Afternoon" is often ranked among the greatest silent comedies, at least where short subjects are concerned, and therefore may come as a bit of a letdown for some. Unlike some of the other recognized classics such as Keaton\'s "Cops" or Chaplin\'s "The Immigrant" this film is in some respects a familiar, conventional situation comedy and doesn\'t offer much in the way of belly laughs; one may even wonder whether Langdon belongs in such rarefied company. Nonetheless, in my opinion, it\'s a perfectly charming comedy in its minor-key way, and Harry is fascinating to watch.<br /><br />For a modern viewer raised on TV sitcoms the plot of "Saturday Afternoon" may suggest The Honeymooners or its many spin-offs: two dim guys, one of whom is married and very much under his wife\'s thumb, try to sneak out with a couple of good-time girls for a fun afternoon; but everything goes wrong, and they wind up having to fight the girl

In [68]:
for item in test_neg_reviews.take(2):
    print(item)
    print(' ')

(<tf.Tensor: shape=(), dtype=string, numpy=b"This movie is, in all likelihood, the worst film ever made. It is certainly the worst that I've ever seen, and I have seen A LOT of bad movies.<br /><br />In this, nothing at all interesting happens throughout the movie. One could, literally, start the movie, take a short nap, and then wake up secure in the knowledge that nothing interesting has happened while you are sleeping. And I have seen this movie three times, staying awake throughout. I feel I should be congratulated.<br /><br />The movie goes as one might expect, according to a formula, with no variation. Hunters capture baby bigfoot, get killed by parent, and the nearby town goes into a bigfoot killing frenzy. This is surprisingly boring for a Troma release.<br /><br />So please do yourself a favor, and skip this movie. If you have to see it you will understand why.">, <tf.Tensor: shape=(), dtype=int64, numpy=0>)
 
(<tf.Tensor: shape=(), dtype=string, numpy=b"In Bollywood it isn't 

In [69]:
buffer_size = 10000
valid_dataset = valid_pos_reviews.concatenate(valid_neg_reviews).shuffle(buffer_size = buffer_size)

In [70]:
valid_batch = valid_dataset.map(lambda X,y: 
                                (string_transform(X), y) ).batch(batch_size).prefetch(prefetch)

In [71]:
test_dataset = test_pos_reviews.concatenate(test_neg_reviews).shuffle(buffer_size)

In [72]:
test_batch = test_dataset.map(lambda X,y: 
                                (string_transform(X), y) ).batch(batch_size).prefetch(prefetch)

In [73]:
testing =test_dataset.map(lambda X,y: 
                                (text_to_integers(string_transform(X)), y) )

In [74]:
it = next(iter(testing))
it

(<tf.Tensor: shape=(290,), dtype=int64, numpy=
 array([68165, 67404, 40322, 53730,  7234, 39897,  1952, 53730, 47496,
        14407, 55549,   135, 51457,  3443,  8482, 68165, 67404, 24156,
        54077, 64890, 63680, 29750, 64318,   904, 51749, 14407, 60922,
        54668, 68165,  6538, 50021, 36853, 38757, 54738,  2613, 55572,
        64049, 14407,  7034, 54077, 69880, 55362, 14407, 38757, 54738,
         7034, 54192, 11251,  6631, 14407, 26291,  3809,  7034, 74268,
        66042, 27334, 65225,  8278, 19720, 28164, 51766,  3809, 26678,
        46971, 27495, 74253, 68165, 27927, 55498, 22149,  6626,  7234,
         6026, 36228, 29302, 23242, 27927, 27927, 13219, 54609, 14912,
        71133,  7234, 58408, 60852,  3809, 44613, 74942, 21260, 51385,
         9114, 12398, 53730, 25838, 68087,  7234, 17744, 32230, 24932,
        12509,  3809, 73108,  4024, 45023, 72608, 44352, 67509, 17837,
         8278,  3809, 38195, 65225,  1030, 44992, 67509, 52274, 43920,
        68165, 57503, 67404, 4